# Generated by Django 3.1.7 on 2021-03-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Req",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("0", "GET"),
                            ("1", "POST"),
                            ("2", "PUT"),
                            ("3", "DELETE"),
                            ("4", "HEAD"),
                        ],
                        max_length=1,
                    ),
                ),
                ("url", models.CharField(max_length=500)),
            ],
        ),
    ]
