# Generated by Django 3.1.7 on 2021-03-02 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reqs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="req",
            name="exec_date",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 3, 2, 9, 3, 0, 938130)
            ),
        ),
    ]
