# Generated by Django 3.1.7 on 2021-03-02 01:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reqs", "0002_req_exec_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="req",
            name="exec_date",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 3, 2, 9, 33, 30, 650670)
            ),
        ),
        migrations.CreateModel(
            name="Resp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "req",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reqs.req"
                    ),
                ),
            ],
        ),
    ]
