# Generated by Django 3.1.7 on 2021-03-02 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reqs", "0003_auto_20210302_0933"),
    ]

    operations = [
        migrations.AddField(
            model_name="resp",
            name="body",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resp",
            name="status",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="req",
            name="exec_date",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 3, 2, 9, 39, 14, 558815)
            ),
        ),
    ]
