# Generated by Django 3.1.7 on 2021-03-02 09:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reqs", "0007_auto_20210302_1119"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resp",
            name="id",
        ),
        migrations.AlterField(
            model_name="req",
            name="exec_date",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 3, 2, 17, 58, 19, 773827)
            ),
        ),
        migrations.AlterField(
            model_name="req",
            name="type",
            field=models.CharField(
                choices=[
                    ("0", "GET"),
                    ("1", "POST"),
                    ("2", "PUT"),
                    ("3", "DELETE"),
                    ("4", "HEAD"),
                ],
                default="0",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="req",
            name="url",
            field=models.CharField(
                default="https://api.github.com/repos/stoplightio/prism/stats/contributors",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="resp",
            name="req",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="reqs.req",
            ),
        ),
    ]
